/**
 * The `eztest replay` command.
 *
 * Orchestrates the full Phase 3 Agent Feedback Loop from a saved BugReport JSON file:
 *   1. Load the bug report
 *   2. Generate + run a reproduction test (should FAIL — bug is present)
 *   3. Analyze the source code and apply an AI-generated code fix
 *   4. Re-run the reproduction test (should PASS — fix is applied)
 *   5. Generate + run a validation suite (positive + negative tests)
 *
 * Usage:
 *   eztest replay --report ./bug-reports/bug-report-abc123.json \
 *                 --source ./src \
 *                 --url http://localhost:3000
 */
import { readFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import type { Command } from 'commander';
import { loadConfig } from '../../shared/config.js';
import { AiClient } from '../../shared/aiClient.js';
import { logInfo, logSuccess, logError, logWarning, enableVerboseLogging } from '../../shared/logger.js';
import type { BugReport } from '../../shared/types.js';
import { generateAndRunReproductionTest } from '../../agentLoop/testReproducer.js';
import { analyzeAndApplyCodeFix } from '../../agentLoop/codeFixAgent.js';
import { generateAndRunValidationSuite } from '../../agentLoop/validationSuite.js';

// ── Types ──────────────────────────────────────────────────────────────────

/** Summary of the completed replay session, printed to stdout at the end. */
interface ReplaySessionSummary {
  bugReportId: string;
  wasReproductionSuccessful: boolean;
  wasFixApplied: boolean;
  doesReproductionTestPass: boolean;
  doesValidationSuitePass: boolean;
  rootCause: string;
  fixDescription: string;
}

// ── Bug Report Loading ─────────────────────────────────────────────────────

/**
 * Loads and parses a BugReport JSON file from disk.
 * Validates that the file exists and contains the required fields.
 */
function loadBugReportFromFile(reportFilePath: string): BugReport {
  const absoluteReportPath = resolve(reportFilePath);

  if (!existsSync(absoluteReportPath)) {
    throw new Error(`Bug report file not found: ${absoluteReportPath}`);
  }

  let rawContent: string;
  try {
    rawContent = readFileSync(absoluteReportPath, 'utf-8');
  } catch (readError) {
    throw new Error(`Could not read bug report file: ${String(readError)}`);
  }

  let parsedReport: unknown;
  try {
    parsedReport = JSON.parse(rawContent);
  } catch {
    throw new Error(`Bug report file is not valid JSON: ${absoluteReportPath}`);
  }

  // Basic validation — ensure the key fields are present
  if (
    typeof parsedReport !== 'object' ||
    parsedReport === null ||
    !('reportId' in parsedReport) ||
    !('userExpectation' in parsedReport) ||
    !('interactionHistory' in parsedReport)
  ) {
    throw new Error(
      `Bug report is missing required fields (reportId, userExpectation, interactionHistory). ` +
      `Was this file generated by \`eztest record\`?`
    );
  }

  return parsedReport as BugReport;
}

// ── Summary Printer ────────────────────────────────────────────────────────

/**
 * Prints a human-readable summary table of the replay session results.
 */
function printReplaySummary(summary: ReplaySessionSummary): void {
  const checkMark = (isPassed: boolean) => isPassed ? '✅' : '❌';

  console.log('\n═══════════════════════════════════════════════');
  console.log('  EZTest Replay — Session Summary');
  console.log('═══════════════════════════════════════════════');
  console.log(`  Bug Report:    ${summary.bugReportId}`);
  console.log(`  Root Cause:    ${summary.rootCause}`);
  console.log(`  Fix Applied:   ${summary.fixDescription}`);
  console.log('───────────────────────────────────────────────');
  console.log(`  ${checkMark(summary.wasReproductionSuccessful)} Reproduction   (test confirms bug is present)`);
  console.log(`  ${checkMark(summary.doesReproductionTestPass)} Fix Verified    (reproduction test now passes)`);
  console.log(`  ${checkMark(summary.doesValidationSuitePass)} Validation      (positive + negative tests pass)`);
  console.log('═══════════════════════════════════════════════\n');
}

// ── Command Registration ───────────────────────────────────────────────────

/**
 * Registers the `replay` subcommand on the given Commander program instance.
 * This command drives the full autonomous test-fix-validate loop.
 */
export function registerReplayCommand(program: Command): void {
  program
    .command('replay')
    .description(
      'Run the full autonomous feedback loop from a saved bug report: ' +
      'reproduce the bug → analyze and fix the code → run validation suite. ' +
      'Requires a live application at --url and an AI API key in the environment.'
    )
    .requiredOption(
      '-r, --report <path>',
      'Path to the BugReport JSON file (generated by `eztest record`)',
    )
    .option(
      '-s, --source <directory>',
      'Source code directory to analyze for the fix',
      './src',
    )
    .option(
      '-u, --url <url>',
      'URL where the target application is running',
      'http://localhost:3000',
    )
    .option(
      '--working-dir <directory>',
      'Project root directory (where playwright.config.ts lives)',
      '.',
    )
    .option(
      '--skip-fix',
      'Only run the reproduction step — do not apply a fix or run validation',
    )
    .option(
      '--skip-validation',
      'Apply the fix but skip the validation suite',
    )
    .option(
      '-v, --verbose',
      'Enable verbose debug logging',
    )
    .action(async (commandOptions: {
      report: string;
      source: string;
      url: string;
      workingDir: string;
      skipFix: boolean;
      skipValidation: boolean;
      verbose: boolean;
    }) => {
      if (commandOptions.verbose) {
        enableVerboseLogging();
      }

      const ezTestConfig = loadConfig();
      const projectRoot = resolve(commandOptions.workingDir);

      logInfo('Starting EZTest replay...');
      logInfo(`  Report:    ${commandOptions.report}`);
      logInfo(`  Source:    ${commandOptions.source}`);
      logInfo(`  App URL:   ${commandOptions.url}`);
      logInfo(`  Project:   ${projectRoot}`);

      // ── Load bug report ──
      let bugReport: BugReport;
      try {
        bugReport = loadBugReportFromFile(commandOptions.report);
        logSuccess(`Loaded bug report: ${bugReport.reportId}`);
        logInfo(`  User expected: "${bugReport.userExpectation}"`);
      } catch (loadError) {
        logError('Failed to load bug report', loadError);
        process.exit(1);
      }

      // ── Initialize AI client ──
      const aiClient = new AiClient(ezTestConfig.ai);
      try {
        await aiClient.initialize();
        logInfo(`  AI: ${aiClient.providerName} / ${aiClient.modelName}`);
      } catch (initError) {
        logError('Failed to initialize AI client', initError);
        logError('Make sure OPENAI_API_KEY or ANTHROPIC_API_KEY is set in your environment.');
        process.exit(1);
      }

      // Track results for summary
      const sessionSummary: ReplaySessionSummary = {
        bugReportId: bugReport.reportId,
        wasReproductionSuccessful: false,
        wasFixApplied: false,
        doesReproductionTestPass: false,
        doesValidationSuitePass: false,
        rootCause: 'Not analyzed',
        fixDescription: 'Not applied',
      };

      // ── Stage 1: Reproduce ──
      logInfo('\n── Stage 1: Reproducing the bug ──');
      let reproductionAttempt;
      try {
        reproductionAttempt = await generateAndRunReproductionTest(bugReport, aiClient, {
          projectRoot,
          targetAppUrl: commandOptions.url,
        });
        sessionSummary.wasReproductionSuccessful = reproductionAttempt.wasReproductionSuccessful;
      } catch (reproductionError) {
        logError('Reproduction step failed unexpectedly', reproductionError);
        process.exit(1);
      }

      if (!reproductionAttempt.wasReproductionSuccessful) {
        logWarning(
          'Bug could not be reproduced automatically. ' +
          'Review the generated test and ensure the app is running at the specified URL.'
        );
        // Allow continuing — the fix may still be useful even without confirmed reproduction
      }

      if (commandOptions.skipFix) {
        printReplaySummary(sessionSummary);
        process.exit(0);
      }

      // ── Stage 2: Fix ──
      logInfo('\n── Stage 2: Analyzing and fixing the bug ──');
      let codeFixResult;
      try {
        codeFixResult = await analyzeAndApplyCodeFix(reproductionAttempt, bugReport, aiClient, {
          projectRoot,
          targetAppUrl: commandOptions.url,
          sourceDirectory: resolve(commandOptions.source),
        });
        sessionSummary.wasFixApplied = codeFixResult.changedFiles.size > 0;
        sessionSummary.doesReproductionTestPass = codeFixResult.doesReproductionTestPass;
        sessionSummary.fixDescription = codeFixResult.fixDescription;

        // Extract just the root cause from the combined fix description
        const fixDescriptionParts = codeFixResult.fixDescription.split(' — ');
        sessionSummary.rootCause = fixDescriptionParts[0] ?? codeFixResult.fixDescription;
      } catch (fixError) {
        logError('Fix step failed unexpectedly', fixError);
        process.exit(1);
      }

      if (!codeFixResult.doesReproductionTestPass) {
        logWarning(
          'The reproduction test still fails after applying the fix. ' +
          'The fix may be incomplete — review the changed files and re-run.'
        );
      }

      if (commandOptions.skipValidation) {
        printReplaySummary(sessionSummary);
        process.exit(0);
      }

      // ── Stage 3: Validate ──
      logInfo('\n── Stage 3: Running validation suite ──');
      try {
        const validationResult = await generateAndRunValidationSuite(
          codeFixResult,
          bugReport,
          reproductionAttempt.reproductionTestCode,
          aiClient,
          {
            projectRoot,
            targetAppUrl: commandOptions.url,
          },
        );
        sessionSummary.doesValidationSuitePass = validationResult.didAllValidationTestsPass;
      } catch (validationError) {
        logError('Validation step failed unexpectedly', validationError);
        process.exit(1);
      }

      // ── Final Summary ──
      printReplaySummary(sessionSummary);

      // Exit with failure if not all stages succeeded — useful for CI pipelines
      const isFullySuccessful =
        sessionSummary.wasReproductionSuccessful &&
        sessionSummary.doesReproductionTestPass &&
        sessionSummary.doesValidationSuitePass;

      if (!isFullySuccessful) {
        process.exit(1);
      }
    });
}
